### PR TITLE
Add UI design for Garden City Ruby Camp 2016

### PR DESCRIPTION
**Pull request by cgirish**
cc/ @kgrz

### CODE REVIEW

**Comment by swanandp** [comment]
Can you please post screenshots / deploy this somewhere ?

**Comment by cgirish** [comment]
deployed url can be see below.

**Comment by swanandp** [comment]
Cool, thanks. Will proof read tomorrow.

**Comment by codemancers-chatops** [comment]
Deployed branch gardencityrubycamp-2016 at url: [web (port: 4000)](http://weathered-glade-8106.46.4.126.75.xip.io)

**Comment by codemancers-chatops** [comment]
Deployed branch gardencityrubycamp-2016 at url: [web (port: 4000)](http://divine-frost-7145.46.4.126.75.xip.io)

**Comment by codemancers-chatops** [comment]
Deployed branch gardencityrubycamp-2016 at url: [web (port: 4000)](http://young-wave-1603.46.4.126.75.xip.io)

**Comment by codemancers-chatops** [comment]
Deployed branch gardencityrubycamp-2016 at url: [web (port: 4000)](http://quiet-pine-8890.46.4.126.75.xip.io)

**Comment by kgrz** [comment]
Some observations:
1. "Garden City Ruby Camp" can get confusing. I think we should have a some kind of writeup for this saying why the name change.
2. Can the workshop descriptions be placed side-by-side? (If there are only two)
3. "React on Rails Workshop" the title should not have "workshop" since it doesn't say so in the left link below register.
4. We can lose the "workshop" think below the Register button if we can have a detailed description about 1.

**Comment by codemancers-chatops** [comment]
Deployed branch gardencityrubycamp-2016 at url: [web (port: 4000)](http://dark-morning-8957.46.4.126.75.xip.io)

**Comment by swanandp** [comment]
Do I need DNS settings? Because the link above just shows nginx page to me

**Comment by emilsoman** [comment]
Once a PR is merged, the staging environment is automatically destroyed.
You can deploy any branch on-demand using the command `olaf deploy
<branchname>` in slack

**Pull request merged**
